/**
 * GENERATED FILE — do not edit manually.
 *
 * This file is generated by running:
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_allocation
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_allocationperiod
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_area
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_assignment
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_resource
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_serviceorinitiative
 *   pac code add-data-source --environment "portfolioshapingdev" --entity systemuser
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_managersummary
 *   pac code add-data-source --environment "portfolioshapingdev" --entity cai_serviceinitiativesummary
 *
 * After running these commands, regenerate this file by running:
 *   npx power-apps init
 *
 * See README.md for the full setup guide.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const dataSourcesInfo: any = {};
